server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect